### ISSUE TITLE
Uncaught TypeError: Cannot read property 'null' of undefined

### ISSUE THREAD

**Issue by emkerber** [jiborobot/jibo-sdk#10]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [jibo-sdk](https://github.com/jiborobot/jibo-sdk) package, v1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'null' of undefined

```
At /Users/kerberem/.atom/packages/jibo-sdk/node_modules/react/lib/ReactMount.js:636

TypeError: Cannot read property 'null' of undefined
    at Object.ReactMount.findReactContainerForID (/Users/kerberem/.atom/packages/jibo-sdk/node_modules/react/lib/ReactMount.js:636:50)
    at findParent (/Users/kerberem/.atom/packages/jibo-sdk/node_modules/react/lib/ReactEventListener.js:39:30)
    at handleTopLevelImpl (/Users/kerberem/.atom/packages/jibo-sdk/node_modules/react/lib/ReactEventListener.js:74:16)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/kerberem/.atom/packages/jibo-sdk/node_modules/react/lib/Transaction.js:134:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/kerberem/.atom/packages/jibo-sdk/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
    at Object.batchedUpdates (/Users/kerberem/.atom/packages/jibo-sdk/node_modules/react/lib/ReactUpdates.js:110:20)
    at ReactEventListener.dispatchEvent (/Users/kerberem/.atom/packages/jibo-sdk/node_modules/react/lib/ReactEventListener.js:174:20)
```

### Commands

```
  2x -6:46.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -6:45.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -6:45.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -6:45.5.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -6:33.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -6:29 editor:newline (atom-text-editor.editor.is-focused)
     -6:12.4.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:11.5.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -6:08.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -6:05.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:56.3.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -5:53.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:34 core:move-down (atom-text-editor.editor.is-focused)
 15x -3:34.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:08.9.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -3:08.2.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
audio, v1.5.6
autoclose-html, v0.23.0
browser-plus-zoom, v0.0.1
file-icons, v1.7.16
jibo-sdk, v1.7.1
linter, v1.11.14
linter-eslint, v7.2.3
merge-conflicts, v1.4.4
minimap, v4.24.7
minimap-highlight-selected, v4.4.0
rest-client, v1.1.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by csaund** [comment]
Hey @emkerber, thanks for reporting. The react errors you'll see in the SDK are driving us nuts, too. We're working on upgrading our React version -- they deprecated some APIs so we have to rework things. We're hoping to push a new version soon!

**Comment by JohnWRobo** [comment]
Hi @emkerber 

Thank you again for reporting this! 

Would you be able to provide a little detail around what you were doing in the tool when this error appeared?

Internally we are seeing it when the command `atom .` is used in terminal to open a skill file and then the same `atom . `command is used again when that file is still open.  Instead of bringing the file up again it will throw the error you reported. 

Let me know if you are seeing that behavior under a different set of circumstances.  

As casaund mentioned, we're working to get this resolved soon but as a workaround in the meantime I recommend clicking on the Atom app in your mac toolbar to bring up a file you already have opened in the tool. 

Thank you again!

**Comment by emkerber** [comment]
Hi John and team,

I actually haven't been working with the Jibo SDK, I've been working with the MEAN stack when the errors occur (there have been a couple instances). Now that you mention it, I only ever get errors when I have two Atom windows open (not tabs of course, windows). I mainly open Atom from the terminal, but I usually have two different projects open in the two Atom windows so I don't think I'm reopening files. There are almost always files with the same names open in both windows though (like index.html, or server.js). But, now that I think about it, I am bringing into Atom, but not opening, folders containing different instances of the same Node modules. Also, it's probably worth mentioning that when the errors occur, they only appear in the second Atom window.

Thanks for all the awesome work your team is doing!! Can't wait til October!! (But I won't be mad if more time is still needed. I get it.)  :)

Liz Kerber
