### ISSUE TITLE
Uncaught TypeError: Cannot read property 'showSaveDialog' of undefined

### ISSUE THREAD

**Issue by shreyapat** [jiborobot/jibo-sdk#14]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.2
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.5
**Thrown From**: [jibo-sdk](https://github.com/jiborobot/jibo-sdk) package, v1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'showSaveDialog' of undefined

```
At /Users/shreyapatel/.atom/packages/jibo-sdk/lib/jibo-sdk.js:19

TypeError: Cannot read property 'showSaveDialog' of undefined
    at o (/Users/shreyapatel/.atom/packages/jibo-sdk/lib/jibo-sdk.js:19:14599)
    at atom-workspace.jibo-sdk:new-rule-file (/Users/shreyapatel/.atom/packages/jibo-sdk/lib/jibo-sdk.js:20:309)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1136:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:319:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -8:21.2.0 jibo-sdk:new-project (div.package-detail.panels-item)
     -8:18 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:57.7.0 jibo-sdk:delete-behavior (span.)
     -2:50 jibo-sdk:add-child (span.)
     -0:00.2.0 jibo-sdk:new-rule-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no"
  },
  "jibo-sdk": {
    "BehaviorEditor": "[{\"size\":-4,\"children\":[{\"size\":-24,\"children\":[]},{\"size\":-24,\"children\":[]}]},{\"size\":-4,\"children\":[{\"size\":-24,\"children\":[]},{\"size\":-24,\"children\":[]}]}]"
  }
}
```

### Installed Packages

```coffee
# User
jibo-sdk, v1.7.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by JohnWRobo** [comment]
Hello @shreyapat, 

Thank you for opening this issue. 

It turns out that this error in the SDK is caused by the most recent update that Atom made to their platform (1.12.2) and the best fix for the moment is to roll back to the last stable version of Atom.

I'm going to provide steps on how to roll back to an earlier version but I also want to make sure you know that you can avoid automatically updating to new versions of Atom by going to **Atom -> preferences -> core** in atom and unchecking the "Automatically Update" box on that page.

To roll back to the last stable version of Atom you can go to Atom's releases page on github for the last compatible release [here](https://github.com/atom/atom/releases/tag/v1.11.1). You can download the appropriate zip for your operating system (atom-mac.zip or atom-windows.zip) to get that version of Atom.

On Mac this will create a second application (by default it is usually called Atom 2 ). If you open this it should allow you to use the SDK as normal but without this NLU issue caused by the recent Atom update.

On Windows the steps are the same but you may also need to re-download AtomSetup.exe from that release page to initially launch the program or you can use file explorer to locate Users//AppData/Local/atom/app-1.11.1 and click "app" to launch the rolled back version of Atom.

Keep in mind, if you are used to opening your Jibo skill from the command line you may need to open it using File -> Open in Atom so that it does not open by default in the 1.11.1 version that is seeing this issue.

If you see any further issues you should also feel free to post to the support section of our dedicated SDK developer forum [here](https://discuss.jibo.com/c/jibo-sdk/support). 

Thank you for your time and patience as I got back to you! :) 

-John
