### ISSUE TITLE
Error: Cannot find module 'pixi.js/bin/pixi.min.js'

### ISSUE THREAD

**Issue by jfaneuff** [jiborobot/jibo-sdk#16]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [jibo-sdk](https://github.com/jiborobot/jibo-sdk) package 1.7.1

### Stack Trace

Failed to load the jibo-sdk package

```
At Cannot find module 'pixi.js/bin/pixi.min.js'

Error: Cannot find module 'pixi.js/bin/pixi.min.js'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.4/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:415)
    at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:606
    at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:22441)
    at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:555)
    at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:722)
    at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:739
    at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:86)
    at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:284)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:410)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:601
    at /packages/jibo-sdk/lib/jibo-sdk.js:18:30496)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:550)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:601
    at /packages/jibo-sdk/lib/jibo-sdk.js:13:18922)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:550)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:601
    at /packages/jibo-sdk/lib/jibo-sdk.js:12:28774)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:550)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:601
    at /packages/jibo-sdk/lib/jibo-sdk.js:10:27286)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:550)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:601
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:2018)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:550)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:601
    at /packages/jibo-sdk/lib/jibo-sdk.js:19:29613)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:550)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:717)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:734
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:85)
    at /packages/jibo-sdk/lib/jibo-sdk.js:9:279)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/jibo-sdk/index.js:1:97)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:548:30)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:439:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:69:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:303:11)
    at /app.asar/src/buffered-process.js:333:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -8:53.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
jibo-sdk 1.7.1 
```

**Comment by joe-tinkham** [comment]
Hi @jfaneuff jfaneuff, the [error](https://discuss.jibo.com/t/pixi-errors-in-jibo-sdk/1423) you are seeing is because of an issue with pixi.js and Atom versions from the installation steps of our [Getting Started Guide](https://developers.jibo.com/docs/installation.html#windows).

In Terminal, run these commands to install the right versions of `pixi.js@4.0.3` and `husl@6.0.1`:
```
cd $HOME; npm install pixi.js@4.0.3
cd $HOME; cd .atom/packages/jibo-sdk; npm install husl@6.0.1
```

Please also make sure to install [Atom v.1.11.1](https://github.com/atom/atom/releases/download/v1.11.1/AtomSetup.exe) as newer versions of Atom (i.e. v.1.14.4) are not yet supported in Jibo-SDK v.1.7.1.

After installing these versions, make sure to close and reopen Atom.

**Comment by jfaneuff** [comment]
That did the trick. Thank you.

**Comment by joe-tinkham** [comment]
@jfaneuff it looks like a problem downloading the `husl@6.0.1` package. I was able to reproduce this issue sometimes on my windows machine. I haven't noticed a huge impact on the SDK by keeping it at the currently installed `husl@5.0.3` version and you should be ok using the SDK in its current state.

If you do notice any issues with color pickers, you can manually download `husl@6.0.1` package [here](https://registry.npmjs.org/husl/-/husl-6.0.1.tgz). After you untar the `husl-6.0.1.tgz` file, move the contents of the `package` directory to `.atom/packages/jibo-sdk/node_modules/husl` directory and replacing the contents.
