### ISSUE TITLE
Atom: Failed to load the jibo-sdk package

### ISSUE THREAD

**Issue by mosaick00** [jiborobot/jibo-sdk#18]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [jibo-sdk](https://github.com/jiborobot/jibo-sdk) package 1.7.1

### Stack Trace

Failed to load the jibo-sdk package

```
At Cannot find module 'pixi.js/bin/pixi.min.js'

Error: Cannot find module 'pixi.js/bin/pixi.min.js'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (/Users/winston/Downloads/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:415)
  at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:606
  at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:22441)
  at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:555)
  at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:722)
  at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:739
  at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:86)
  at /packages/jibo-sdk/node_modules/pixi-animate/dist/pixi-animate.min.js:7:284)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:410)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:601
  at /packages/jibo-sdk/lib/jibo-sdk.js:18:30496)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:550)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:601
  at /packages/jibo-sdk/lib/jibo-sdk.js:13:18922)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:550)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:601
  at /packages/jibo-sdk/lib/jibo-sdk.js:12:28774)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:550)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:601
  at /packages/jibo-sdk/lib/jibo-sdk.js:10:27286)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:550)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:601
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:2018)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:550)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:601
  at /packages/jibo-sdk/lib/jibo-sdk.js:19:29613)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:550)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:717)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:734
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:85)
  at /packages/jibo-sdk/lib/jibo-sdk.js:9:279)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/jibo-sdk/index.js:1:97)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
  at /app.asar/src/package.js:123:28
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:548:30)
  at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
  at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
  at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
  at /app.asar/src/buffered-process.js:352:11)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

```

### Commands

```
  3x -1:31.9.0 core:backspace (input.hidden-input)
     -1:30.9.0 core:paste (input.hidden-input)
     -1:29.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
audio 1.5.7 
jibo-sdk 1.7.1 
```

**Comment by JohnWRobo** [comment]
Hello @mosaick00 it looks like you are seeing this error because pixi.js is not installed as mentioned in our [installation documentation here](https://developers.jibo.com/docs/index.html#installation-1).

You can check out step 7 of that installation section I linked above or you can view issue #16  where a user encountered the same thing.

**Comment by johanschalkwyk** [comment]
I have the same issue.

cleaned out .atom/
re-installed atom
re-install jibo-sdk
re-install pixi

restart atom
no luck.

**Comment by JohnWRobo** [comment]
Hi @johanschalkwyk 

Could you confirm if you are installing the pixi.js node module in your home directory at version 4.0.3 as mentioned in [this section](https://developers.jibo.com/docs/index.html#install-the-jibo-atom-package) of our install guide and as seen here:

```
cd $HOME
npm install pixi.js@4.0.3
cd .atom/packages/jibo-sdk
npm install husl@6.0.1
```

If you install that node module in a different directory or at a different version you will not be able to activate the installed jibo-sdk package in Atom.  We have seen instances where installing husl is not needed but pixi.js needs to be installed at your home directory and at version 4.0.3 for the package to work. 

If you do have pixi installed in that way and are still seeing this issue I would like to confirm some details about your setup and the SDK's dependencies so I can recommend next steps and make sure your installation is being done in the best fashion.

General system info:
* Operating System:
* Amount of RAM: 
* Node Version:
* Atom version:

If you are using Windows

* Command line tool (Git Shell or Git Bash):
* Visual Studio Version:

If you are using Mac

* Do you have Xcode command line tools installed? (xcode-select --install in terminal) 

If you can reply back with that info I can make sure to take a closer look for you and recommend any next steps possible.

**Comment by johanschalkwyk** [comment]
Thank you for the help.

I had pixi install globally under /usr/local/lib/node_modules. Removing
that and re-installing from $HOME fixed it.
