### ISSUE TITLE
Uncaught InvalidStateError: Failed to execute 'start' on 'AudioBufferSourceNode': The offset prov...

### ISSUE THREAD

**Issue by alfarmer** [jiborobot/jibo-sdk#8]
[Enter steps to reproduce below:]
1. adding audio event and .mp3 to a .key file and play.

adding .mp3 file from selection UI  by selecting Audio Event selecting my .mp3 
[Jibo Files.zip](https://github.com/jiborobot/jibo-sdk/files/312885/Jibo.Files.zip)

and using the 's' key on the keyboard to add the audio, move the slider past the audio wave and hit the 's' key again, select the same .mp3 file to get the sound to repeat.

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [jibo-sdk](https://github.com/jiborobot/jibo-sdk) package, v1.7.1

### Stack Trace

Uncaught InvalidStateError: Failed to execute 'start' on 'AudioBufferSourceNode': The offset provided (-0.040625) is less than the minimum bound (0).

```
At /Users/alfarmer/.atom/packages/jibo-sdk/lib/jibo-sdk.js:9

Error: Failed to execute 'start' on 'AudioBufferSourceNode': The offset provided (-0.040625) is less than the minimum bound (0).
    at Error (native)
    at e.n.set (/Users/alfarmer/.atom/packages/jibo-sdk/lib/jibo-sdk.js:9:8226)
    at e.o.value (/Users/alfarmer/.atom/packages/jibo-sdk/lib/jibo-sdk.js:9:16940)
    at e.o.value (/Users/alfarmer/.atom/packages/jibo-sdk/lib/jibo-sdk.js:9:14700)
    at e.o.value (/Users/alfarmer/.atom/packages/jibo-sdk/lib/jibo-sdk.js:9:10431)
    at /Users/alfarmer/.atom/packages/jibo-sdk/lib/jibo-sdk.js:9:12847
    at Array.forEach (native)
    at e.o.value (/Users/alfarmer/.atom/packages/jibo-sdk/lib/jibo-sdk.js:9:12825)
    at emitNone (events.js:72:20)
    at t.emit (events.js:166:7)
    at t.s.value (/Users/alfarmer/.atom/packages/jibo-sdk/lib/jibo-sdk.js:10:15734)
    at t.s.value (/Users/alfarmer/.atom/packages/jibo-sdk/lib/jibo-sdk.js:10:12569)
```

### Commands

```
  2x -5:55.6.0 jibo-sdk:upsert-keyframe (div.)
     -3:35 core:save (atom-pane.pane.active)
  2x -0:21.9.0 jibo-sdk:upsert-keyframe (div.)
     -0:05.7.0 core:save (div.)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "jibo-sdk": {
    "AnimationEditor": "[{\"size\":1353.2501120573734,\"children\":[{\"size\":623.75,\"children\":[{\"size\":1237.0207560816593,\"children\":[]},{\"size\":959.0207560816593,\"children\":[]}]},{\"size\":227.75,\"children\":[]}]},{\"size\":186.74988794262663,\"children\":[]}]",
    "BehaviorEditor": "[{\"size\":700.5,\"children\":[{\"size\":-24,\"children\":[]},{\"size\":-24,\"children\":[]}]},{\"size\":610.5,\"children\":[{\"size\":-24,\"children\":[]},{\"size\":-24,\"children\":[]}]}]",
    "RunConfiguration": {}
  }
}
```

### Installed Packages

```coffee
# User
audio, v1.5.6
jibo-sdk, v1.7.1

# Dev
No dev packages
```

**Comment by alfarmer** [comment]
[test.zip](https://github.com/jiborobot/jibo-sdk/files/315095/test.zip)
Skill Sample where error occurs.
